### PR TITLE
Creating some example bin scripts which use this library.

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
To check if I know how to use the library, I'm creating a few sample scripts.

I'm also proposing 'filedate' as a header that has the date of the stored file, encoded in iso8601 format (Apache uses a different format, but our libraries and databases use ISO8601).

### CODE REVIEW

**Comment by SaschaAdler** [comment]
I've committed your requested fixes to `master`.

**Comment by RussellMcOrmond** [comment]
Any comments on 'filedate'?  It is the modification date of the file, so should we instead use modified-filedate?  Does it matter, as long as we are consistent?


Upload working as expected.  Moving to a download.

Note: Uploaded to default account, as well as to AUTH_crkn

```
tdr@6aa7fc276517:~/CIHM-Swift$ swift-upload.pl --server https://swift.canadiana.ca --user rmcormond --password "xxx" test oocihm.lac_reel_t2170/manifest-md5.txt /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
File date: 2014-04-15T20:38:54Z
Headers from stored object:
accept-ranges: bytes
connection: close
content-length: 108697
content-type: text/plain
date: Fri, 02 Aug 2019 14:31:06 GMT
etag: 4be34a788368e86faee58cad8f04fc46
last-modified: Fri, 02 Aug 2019 14:31:06 GMT
x-object-meta-filedate: 2014-04-15T20:38:54Z
x-openstack-request-id: tx17bc36ba0cac4bf785adf-005d44492a
x-timestamp: 1564756265.13183
x-trans-id: tx17bc36ba0cac4bf785adf-005d44492a

tdr@6aa7fc276517:~/CIHM-Swift$ md5sum /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
4be34a788368e86faee58cad8f04fc46  /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
tdr@6aa7fc276517:~/CIHM-Swift$ stat /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
  File: '/cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt'
  Size: 108697    	Blocks: 97         IO Block: 109056 regular file
Device: 2eh/46d	Inode: 110133414   Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1117/     tdr)   Gid: ( 1117/     tdr)
Access: 2019-08-02 10:31:24.338593963 -0400
Modify: 2014-04-15 16:38:54.000000000 -0400
Change: 2014-05-07 15:05:09.226400958 -0400
 Birth: -
tdr@6aa7fc276517:~/CIHM-Swift$ swift-upload.pl --server https://swift.canadiana.ca --user rmcormond --password "yyyy" --account AUTH_crkn repository oocihm.lac_reel_t2170/manifest-md5.txt /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
File date: 2014-04-15T20:38:54Z
Headers from stored object:
accept-ranges: bytes
connection: close
content-length: 108697
content-type: text/plain
date: Fri, 02 Aug 2019 14:36:16 GMT
etag: 4be34a788368e86faee58cad8f04fc46
last-modified: Fri, 02 Aug 2019 14:36:16 GMT
x-object-meta-filedate: 2014-04-15T20:38:54Z
x-openstack-request-id: txda6a89f104df47539f4f0-005d444a60
x-timestamp: 1564756575.79101
x-trans-id: txda6a89f104df47539f4f0-005d444a60

tdr@6aa7fc276517:~/CIHM-Swift$ 
```

**Comment by SaschaAdler** [comment]
I like `File-Modified` for the header, but it doesn't matter as long as we're consistent.

**Comment by RussellMcOrmond** [comment]
> I like `File-Modified` for the header, but it doesn't matter as long as we're consistent.

Changed.   One possibility is that you add methods for getting and setting that specific header, so the library will help document for consistency.

Download works as expected:

```
tdr@d684b20430d2:~$ swift-download.pl --server https://swift.canadiana.ca --user rmcormond --password "zzz" --account AUTH_crkn repository oocihm.lac_reel_t2170/manifest-md5.txt /tmp/manifest-md5.txt
tdr@d684b20430d2:~$ md5sum /tmp/manifest-md5.txt /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
4be34a788368e86faee58cad8f04fc46  /tmp/manifest-md5.txt
4be34a788368e86faee58cad8f04fc46  /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
tdr@d684b20430d2:~$ ls -l /tmp/manifest-md5.txt /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
-rw-r--r-- 1 tdr tdr 108697 Apr 15  2014 /cihmz/repository/aip/oocihm/792/oocihm.lac_reel_t2170/manifest-md5.txt
-rw-r--r-- 1 tdr tdr 108697 Apr 15  2014 /tmp/manifest-md5.txt
tdr@d684b20430d2:~$ 
```

**Pull request merged**
